services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: khata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - katha_pg_data:/var/lib/postgresql/data/pgdata
volumes:
  katha_pg_data:
