services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: khata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  khata:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      PRIMARY_DB_HOST: postgres
volumes:
  db_data:
